version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      web:
        patterns:
          - "*"
    ignore:
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: cargo
    directories:
      - /tools/*
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      tools:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
